### ISSUE TITLE
December 2023 Meeting - NO MEETING

### ISSUE THREAD

**Issue by 1kevgriff** [Hampton-Roads-Azure/Organization#3]
## Meeting Information

**Meeting Date:**
December 12th, 2023

NO MEETING - KEVIN OUT OF TOWN

**Comment by 1kevgriff** [comment]
@drewgle Recommend canceling - I'll be out of town

**Comment by 1kevgriff** [comment]
LEaving open so we don't forget.

**Comment by drewgle** [comment]
Sounds good.
