### ISSUE TITLE
April 2024 Meeting

### ISSUE THREAD

**Issue by drewgle** [Hampton-Roads-Azure/Organization#5]
## Meeting Information

**Meeting Date:**
2024-04-09

**Meeting Title:** ARM, Bicep, knees and toes! Infrastructure as code for beginners.

Infrastructure as code allows you to deploy cloud resources in a consistent and repeatable manner. Tools like ARM, Bicep and Terraform are used to build templates that make this automation possible, but their syntax can make it challenging to get started.

In this no slides talk, we will explore the differences between these 3 tools, the basic structure for these templates, some tips and tricks to help get you started and how you can deploy resources to the cloud using the command line and deployment pipelines.

By the end of this talk, you'll be ready to integrate infrastructure as code into your resource deployment processes.
 
 **Speaker** Sam Gomez
 
 I've worked in software development for 15+ years (mostly Microsoft technologies) and love the problem-solving aspect of the work. In recent years I have become very passionate about AI and machine learning technologies and how they can be applied to different aspects of our lives. When not coding I enjoy spending time with my family, soccer (watching, playing, and coaching), playing videogames and watching movies.

**Comment by 1kevgriff** [comment]
updated
